# Generated by Django 5.2.3 on 2025-07-12 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subscription_plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='free', max_length=50)),
                ('subscribed_on', models.DateTimeField(auto_now_add=True)),
                ('subscription_active', models.BooleanField(default=True)),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('description', models.TextField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.grade')),
            ],
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('recommended_by_ai', models.BooleanField(default=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyProject.course')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.learninggoal')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PathFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.learningpath')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('courses', models.ManyToManyField(blank=True, to='MyProject.course')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.grade')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyProject.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.student_profile')),
            ],
        ),
        migrations.AddField(
            model_name='learningpath',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyProject.student_profile'),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.student_profile'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.student_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('certificate_file', models.FileField(upload_to='certificates/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.student_profile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
                ('submitted', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(to='MyProject.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='student_projects/')),
                ('is_submitted', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.student_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.course')),
            ],
        ),
        migrations.CreateModel(
            name='Quize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question', models.TextField(default='Sample question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pass_score', models.FloatField(default=50.0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.student_profile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.topic')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyProject.topic'),
        ),
        migrations.AddField(
            model_name='project',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.topic'),
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('material_type', models.CharField(choices=[('video', 'Video'), ('document', 'Document'), ('image', 'Image'), ('audio', 'Audio')], max_length=10)),
                ('file', models.FileField(upload_to='materials/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.course')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.topic')),
            ],
        ),
        migrations.CreateModel(
            name='LearningPathTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.learningpath')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.topic')),
            ],
        ),
        migrations.AddField(
            model_name='learningpath',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.topic'),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.course')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.topic')),
            ],
        ),
        migrations.CreateModel(
            name='AI_Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField(help_text='List of options in JSON format')),
                ('correct_answer', models.CharField(max_length=255)),
                ('selected_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('grade_level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.course')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyProject.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicAssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.student_profile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('weak_areas', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.student_profile')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='learningpath',
            unique_together={('goal', 'topic')},
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.student_profile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.topic')),
            ],
            options={
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
