# Generated by Django 5.2.3 on 2025-07-13 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_progress',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyProject.topic'),
        ),
    ]
