# Generated by Django 5.2.3 on 2025-07-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
