# Generated by Django 5.2.3 on 2025-07-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0002_student_profile_email_student_profile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_profile',
            old_name='School',
            new_name='school',
        ),
    ]
