# Generated by Django 5.2.3 on 2025-06-26 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0002_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subscription_plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='free', max_length=50)),
                ('subscribed_on', models.DateTimeField(auto_now_add=True)),
                ('subscription_active', models.BooleanField(default=True)),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student_profile',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyProject.school'),
        ),
    ]
