# Generated by Django 5.2.3 on 2025-07-06 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0003_rename_school_student_profile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyProject.course'),
        ),
    ]
