# Generated by Django 5.2.3 on 2025-07-13 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0003_chathistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='course',
        ),
    ]
