# Generated by Django 5.2.3 on 2025-06-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0003_school_student_profile_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='user',
        ),
    ]
