# Generated by Django 5.2.3 on 2025-06-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0004_remove_students_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
