# Generated by Django 5.2.3 on 2025-07-15 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0004_remove_chathistory_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('awarded_on', models.DateTimeField(auto_now_add=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('criteria', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.student_profile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_on', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.badges')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.student_profile')),
            ],
            options={
                'unique_together': {('student', 'badge')},
            },
        ),
    ]
