# Generated by Django 5.2.3 on 2025-07-06 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0004_alter_student_profile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_progress',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyProject.topic'),
        ),
    ]
