# Generated by Django 5.2.3 on 2025-07-06 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0005_alter_student_progress_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.student_profile')),
            ],
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('recommended_by_ai', models.BooleanField(default=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.learninggoal')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.topic')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('goal', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='PathFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.learningpath')),
            ],
        ),
        migrations.CreateModel(
            name='TopicAssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.student_profile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.topic')),
            ],
        ),
    ]
