# Generated by Django 5.2.3 on 2025-07-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0006_leaderboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badges',
            name='student',
        ),
    ]
