# Generated by Django 5.2.3 on 2025-07-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0006_learninggoal_learningpath_pathfeedback_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='student_profile',
            name='course',
        ),
        migrations.AddField(
            model_name='quize',
            name='question',
            field=models.TextField(default='Sample question'),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='courses',
            field=models.ManyToManyField(blank=True, to='MyProject.course'),
        ),
    ]
