# Generated by Django 5.2.3 on 2025-07-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0007_delete_student_remove_student_profile_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
