# Generated by Django 5.2.3 on 2025-07-11 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0012_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyProject.course'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyProject.student_profile'),
        ),
    ]
