# Generated by Django 5.2.3 on 2025-07-11 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0013_learningpath_course_learningpath_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.student_profile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProject.topic')),
            ],
            options={
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
